# Generated by Django 4.2.4 on 2023-08-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarppt',
            name='test',
        ),
    ]
