# Generated by Django 4.2.4 on 2023-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_seminarppt_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarppt',
            name='uploadDate',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
