# Generated by Django 4.2.4 on 2023-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seminarppt_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarppt',
            name='pptFileName',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
