# Generated by Django 4.2.4 on 2023-09-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarppt',
            name='pptLength',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
