# Generated by Django 4.2.4 on 2023-09-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0002_seminarppt_pptlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarppt',
            name='pptLength',
        ),
    ]
